server.port=8040
spring.application.name=SpringAPIGateway

eureka.client.serviceUrl.defaultZone=http://localhost:8011/eureka

# AUTO ROUTING
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# MANUAL ROUTING
spring.cloud.gateway.routes[0].id=user
spring.cloud.gateway.routes[0].uri=lb://User-MS
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/status/check
spring.cloud.gateway.routes[0].predicates[1]=Method=GET